use apidb;

INSERT INTO appCategory VALUES ('0', 'MAIN', 'Root category', NULL);
UPDATE appCategory SET catId = '0' WHERE catName = 'MAIN' LIMIT 1;
INSERT INTO appCategory VALUES (1, 'Audio', 'Audio related applications', 29);
INSERT INTO appCategory VALUES (2, 'Games', 'Games', 0);
INSERT INTO appCategory VALUES (3, 'Graphics', 'Graphics viewers, editors, graphics demos, screensavers etc.', 29);
INSERT INTO appCategory VALUES (4, 'Productivity', 'Productivity applications', 0);
INSERT INTO appCategory VALUES (5, 'Networking & Communication', 'Network, Internet related programs and comm stuff', 0);
INSERT INTO appCategory VALUES (6, 'Programming / Software Engineering', 'Languages, Compilers, IDEs, CASE tools etc.', 0);
INSERT INTO appCategory VALUES (7, 'Utilities', 'Misc. Utilities', 0);
INSERT INTO appCategory VALUES (8, 'Scientific/Technical/Math', 'Scientific and mathematic applications', 0);
INSERT INTO appCategory VALUES (10, 'File System', 'File System Utilities (e.g. CD writer stuff, file managers, shells, ...)', 7);
INSERT INTO appCategory VALUES (11, 'Compression', 'Compression Tools', 7);
INSERT INTO appCategory VALUES (13, 'Sound Editing', 'Sound editing suites, recorders, mixing and sampling.', 1);
INSERT INTO appCategory VALUES (14, 'Audio Players', 'MP3, WAV, and other format audio players.', 1);
INSERT INTO appCategory VALUES (16, '1st Person Shooter', 'Games such as Doom, Quake, Half-Life.', 2);
INSERT INTO appCategory VALUES (18, 'Graphics Viewer', 'Image viewing', 3);
INSERT INTO appCategory VALUES (19, 'Graphics Editing', 'Image editing/vector drawing software', 3);
INSERT INTO appCategory VALUES (21, 'Animation/Rendering/3D', 'Image animation for multimedia or web', 3);
INSERT INTO appCategory VALUES (23, 'Word Processing', 'Type, edit, print, OCR!', 4);
INSERT INTO appCategory VALUES (24, 'Spreadsheet', 'Do it yourself Number crunching', 4);
INSERT INTO appCategory VALUES (25, 'Database', 'Relational Database', 4);
INSERT INTO appCategory VALUES (26, 'Presentation', 'Slide Shows with animation and sound and flowchart tools', 4);
INSERT INTO appCategory VALUES (27, 'Web Design', 'Create your own web page', 4);
INSERT INTO appCategory VALUES (29, 'Multimedia', 'Graphics, Audio and Video', 0);
INSERT INTO appCategory VALUES (31, 'Video', 'Video players, editors and codecs', 29);
INSERT INTO appCategory VALUES (33, 'Browsers', 'Netscape, Opera, Mozilla, Mosaic, IE, ...', 5);
INSERT INTO appCategory VALUES (35, 'Email, news and Groupware', 'Email and related programs.', 5);
INSERT INTO appCategory VALUES (37, 'Chat, Instant Messaging, Telephony', 'AIM, ICQ, NetMeeting, Speak Freely, ...', 5);
INSERT INTO appCategory VALUES (45, 'Net Tools', 'Tools such as proxies, web crawlers, search engines, ...', 5);
INSERT INTO appCategory VALUES (43, 'Office Suites', 'Productivity apps that contain bundles of applications.', 4);
INSERT INTO appCategory VALUES (47, 'Reference/Documentation/Info', 'Encyclopedias, information resources, data tracking, ...', 0);
INSERT INTO appCategory VALUES (49, 'EDA/Measurement', 'Electronics design tools, measurement and stuff', 8);
INSERT INTO appCategory VALUES (51, 'Mathematics', 'Mathematical and Statistical software.', 8);
INSERT INTO appCategory VALUES (53, 'Text Editors', 'Multipurpose text editing tool. No formatting just text.', 4);
INSERT INTO appCategory VALUES (55, 'Role Playing Games', 'Games where you build up your characters through battle and experience.', 2);
INSERT INTO appCategory VALUES (57, 'Strategy Games', 'Build your army, conquer the world', 2);
INSERT INTO appCategory VALUES (59, 'CAD/CAE', 'Computer Aided Design, Computer Aided Engineering', 8);
INSERT INTO appCategory VALUES (61, 'Office Utilities', 'Misc Office tools that usually work in conjunction with other Office software.', 4);
INSERT INTO appCategory VALUES (63, 'Finance/Accounting/Project/CRM', 'Personal and Business Finance Software and project planning, CRM (Customer Relationship Management).', 4);
INSERT INTO appCategory VALUES (65, 'Emulators', 'Software that emulates game hardware.', 2);
INSERT INTO appCategory VALUES (71, 'Flowchart/Diagraming/graphs', 'Software to design flowcharts and diagrams', 8);
INSERT INTO appCategory VALUES (69, 'Adventures', 'Graphical Adventure Games', 2);
INSERT INTO appCategory VALUES (74, 'File transfer/sharing', 'FTP, NFS, document sharing, Samba, scp, ...', 5);
INSERT INTO appCategory VALUES (76, 'Educational games / children', 'Games that encourage learning.', 2);
INSERT INTO appCategory VALUES (78, 'Card, Puzzle and Board Games', 'Card Games, mind puzzles and \\"traditional\\" stuff.', 2);
INSERT INTO appCategory VALUES (82, 'Educational Software, CBT', 'Educational tools, Computer Based Training', 0);
INSERT INTO appCategory VALUES (84, 'Action Games', 'Arcade and platform action games', 2);
INSERT INTO appCategory VALUES (86, 'Sports Games', 'Professional sports, car racing, and more.', 2);
INSERT INTO appCategory VALUES (88, 'Simulation Games', 'Flight and other real life simulators.', 2);
INSERT INTO appCategory VALUES (90, 'Remote Access', 'SSH, Telnet, VNC, Terminal Services, ...', 5);
INSERT INTO appCategory VALUES (92, 'Desktop Publishing', 'Various page layout, print, and publishing applications.', 4);
INSERT INTO appCategory VALUES (95, 'Graphics demos', '', 3);
INSERT INTO appCategory VALUES (97, 'Game Tools', 'Misc. tools related to games.', 2);
INSERT INTO appCategory VALUES (99, 'Astronomy', 'An endless (almost) empty space... ;-)', 8);
INSERT INTO appCategory VALUES (101, 'Screensavers', 'Run via \\"wine -- ssaver.scr /s\\" to setup', 3);
INSERT INTO appCategory VALUES (103, 'Online (MMORPG) Games', 'Massively Multiplayer Online Role Playing Games.', 2);
INSERT INTO appCategory VALUES (105, 'Special Purpose', 'Very special programs that whole businesses might rely on', 0);
INSERT INTO appCategory VALUES (107, 'Legal/law', '', 4);
INSERT INTO appCategory VALUES (110, 'Biology', 'All kinds of natural things.', 8);
INSERT INTO appCategory VALUES (112, 'Fun stuff', '', 2);
INSERT INTO appCategory VALUES (116, 'Chemistry', 'All kinds of application used for chemistry in science.', 8);
INSERT INTO appCategory VALUES (123, 'Installers', 'Program installers like installshield, windows installer etc.', 0);
INSERT INTO appCategory VALUES (124, 'Electronics design', '', 0);
INSERT INTO appCategory VALUES (125, 'Religious', 'Bible research software, tours of the holy land...', 0);
