#! /bin/sh

echo Create the base user
mysql -p -u root < create_user.sql

echo Create the apidb database, and tables
cat create_apidb_base.sql appdb_tables.sql \
    prefs_list.sql user_list.sql user_prefs.sql \
    user_privs.sql session_list.sql app_category.sql \
    maintainers.sql buglinks.sql monitors.sql \
    error_log.sql distributions.sql testResults.sql \
 | mysql -p -u root
