#! /bin/sh

echo Create the base user
echo NOTE: It's ok for this to fail if the user already exists
echo       there doesn't appear to be a way to create a user only
echo       if they don't exist so we have to live with a potential
echo       error after we try.
mysql -p -u root < create_user.sql

echo Create the apidb database, and tables
cat create_apidb_base.sql appdb_tables.sql \
    prefs_list.sql user_list.sql user_prefs.sql \
    user_privs.sql session_list.sql app_category.sql \
    maintainers.sql buglinks.sql monitors.sql \
    error_log.sql distributions.sql testResults.sql \
 | mysql -p -u root
