#! /bin/sh

echo Creating appdb tables
mysql -p -u root < appdb_tables.sql

echo Creating preferences list
mysql -p -u root < prefs_list.sql

echo Creating user list
mysql -p -u root < user_list.sql

echo Creating user preferences
mysql -p -u root < user_prefs.sql

echo Creating user privilages
mysql -p -u root < user_privs.sql

echo Creating session table
mysql -p -u root < session_list.sql

echo Adding categories
mysql -p -u root < app_category.sql

echo Adding maintainers
mysql -p -u root < maintainers.sql
